import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { z } from 'zod'
import { describe, expect, it } from 'vitest'
import { experimentSchema, executionSchema, evidenceSchema, overviewSchema, reportSchema, pageOf, targetSchema, scenarioSchema } from '../api/contracts'
// Mandatory in CI; generated by ConsoleReadApiTests using actual Spring serialization.
// Local frontend-only runs may omit this integration seam (no invented API fixture).
describe.runIf(process.env.CONSOLE_CONTRACT_DIR)('Spring REST -> TypeScript runtime contracts', () => {
  it('parses actual DTO serialization including legacy UUIDs, NON_NULL and nullable report windows', () => {
    const raw = JSON.parse(readFileSync(resolve(process.env.CONSOLE_CONTRACT_DIR!, 'console-contracts.json'), 'utf8')) as Record<string, unknown>
    const schemas = { experiment: experimentSchema, experiments: pageOf(experimentSchema), execution: executionSchema, executions: pageOf(executionSchema), evidence: evidenceSchema, overview: overviewSchema, reports: pageOf(reportSchema), report: reportSchema, targets: z.array(targetSchema), scenarios: z.array(scenarioSchema) }
    for (const [key, schema] of Object.entries(schemas)) expect(schema.safeParse(raw[key]).success, `wire schema: ${key}`).toBe(true)
    expect(evidenceSchema.parse(raw.evidence).physicalRecovery).toBe('UNKNOWN')
    expect(reportSchema.parse(raw.report).conclusionStatus).toBe('INSUFFICIENT_DATA')
  })
})
