spring:
  application:
    name: chaoslab-backend
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
